<?php

/**
 * @file
 * Ai myfeed module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Component\Render\PlainTextOutput;
use Drupal\Component\Utility\Html;
use Drupal\taxonomy\Entity\Term;
use Drupal\user\Entity\User;


/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function ai_myfeed_theme($existing, $type, $theme, $path) {
  return [
        'ai_myfeed_page' => [
            'variables' => ['my_feed_data' => NULL,'feed_click_message'=>NULL,'feed_message'=>NULL],
        ],
    ];
}

/**
 * Implements hook_views_data_alter().
 */
function ai_myfeed_views_data_alter(array &$data) {
  $data['node']['feed_filter'] = [
    'title' => t('Feed filter'),
    'filter' => [
      'title' => t('Feed filter'),
      'help' => t('Provides a custom filter for my feed.'),
      'field' => 'nid',
      'id' => 'myfeed_views_filter',
    ],
  ];
}

?>